# Generated by Django 4.1.3 on 2022-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(null=True),
        ),
    ]
